package com.edgareldy.micronauttutorial.repository;

import com.edgareldy.micronauttutorial.entity.Permission;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

/**
 * Data access for permissions (unique per resource and action). Implementation generated by Micronaut Data.
 * <p>
 * Created edgar.muhamyangabo on 9/19/26
 * Author : edgar.muhamyangabo
 * Date : 9/19/26
 * Project : micronaut-tutorial
 */
@Repository
public interface PermissionRepository extends JpaRepository<Permission, Long> {

    Optional<Permission> findByResourceAndAction(String resource, String action);

    boolean existsByResourceAndAction(String resource, String action);

    List<Permission> findAllOrderById();
}
