package com.edgareldy.micronauttutorial.repository;

import com.edgareldy.micronauttutorial.entity.Role;
import io.micronaut.data.annotation.Join;
import io.micronaut.data.annotation.Query;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

/**
 * Data access for roles, plus the PostgreSQL advisory lock used to serialise last-admin checks. Implementation generated by Micronaut Data.
 * <p>
 * Created edgar.muhamyangabo on 9/19/26
 * Author : edgar.muhamyangabo
 * Date : 9/19/26
 * Project : micronaut-tutorial
 */
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {

    Optional<Role> findByRoleName(String roleName);

    boolean existsByRoleName(String roleName);

    /** All roles with their permissions loaded in the same query (LEFT JOIN FETCH), ordered by id. */
    @Join(value = "permissions", type = Join.Type.LEFT_FETCH)
    List<Role> findAllOrderById();

    /** How many roles currently hold the permission (deletePermission is refused while this is above zero). */
    @Query("SELECT COUNT(r) FROM Role r JOIN r.permissions p WHERE p.id = :permissionId")
    long countRolesByPermissionId(Long permissionId);

    /**
     * Takes a transaction-scoped PostgreSQL advisory lock on the given key: it blocks until any other
     * transaction holding the same key ends, and is released automatically at commit or rollback.
     * The function is wrapped in a sub-select so the statement returns a row (a bare void function would not).
     */
    @Query(value = "SELECT 1 FROM (SELECT pg_advisory_xact_lock(:key)) t", nativeQuery = true)
    int acquireAdvisoryLock(long key);
}
